export const MENU_NAMES = {
  menswear: {
    value: "Menswear",
    submenu: {
      tops: { value: "Tops", link: "#" },
      bottoms: { value: "Bottoms", link: "#" },
      underwear: { value: "Underwear", link: "#" },
      outerwear: { value: "Outerwear", link: "#" },
      accessories: { value: "Accessories", link: "#" },
      shoes: { value: "Shoes", link: "#" },
    },
  },
  womenswear: {
    value: "Womenswear",
    submenu: {
      tops: { value: "Tops", link: "#" },
      bottoms: { value: "Bottoms", link: "#" },
      dresses: { value: "Dresses", link: "#" },
      lingerie: { value: "Lingerie", link: "#" },
      outerwear: { value: "Outerwear", link: "#" },
      accessories: { value: "Accessories", link: "#" },
      shoes: { value: "Shoes", link: "#" },
      sets: { value: "Sets", link: "#" },
    },
  },
  jewellery: {
    value: "Jewellery",
    submenu: {
      bodyjewellery: { value: "Body jewellery", link: "#" },
      other: { value: "Other", link: "#" },
      bracelets: { value: "Bracelets", link: "#" },
      earrings: { value: "Earrings", link: "#" },
      necklaces: { value: "Neclaces", link: "#" },
      pins: { value: "Pins", link: "#" },
      rings: { value: "Rings", link: "#" },
      watches: { value: "Watches", link: "#" },
    },
  },
  beauty: {
    value: "Beauty",
    submenu: {
      fragrance: { value: "Fragrance", link: "#" },
      hair: { value: "Hair", link: "#" },
      skincare: { value: "Skincare", link: "#" },
      toolsbrushes: { value: "Tools & Brushes", link: "#" },
      bathbody: { value: "Bath & Body", link: "#" },
      makeup: { value: "Makeup", link: "#" },
      other: { value: "Other", link: "#" },
    },
  },
  more: {
    value: "More",
    submenu: {
      art: { value: "Art", link: "#" },
      home: { value: "Home", link: "#" },
      kids: { value: "Kids", link: "#" },
      sportsequipment: { value: "Sports equipment", link: "#" },
      transportation: { value: "Transportation", link: "#" },
      other: { value: "Other", link: "#" },
      booksmagazines: { value: "Books & Magazines", link: "#" },
      film: { value: "Film", link: "#" },
      music: { value: "Music", link: "#" },
      facemasksandcoverings: { value: "Face masks and coverings", link: "#" },
    },
  },
  brands: {
    value: "Brands",
    submenu: {
      nike: { value: "Nike", link: "#" },
      jordan: { value: "Jordan", link: "#" },
      zara: { value: "Zara", link: "#" },
      thenorthface: { value: "The North Face", link: "#" },
      drmartens: { value: "Dr. Martens", link: "#" },
      urbanoutfitters: { value: "Urban Outfitters", link: "#" },
      levis: { value: "Levi's", link: "#" },
      adidas: { value: "Adidas", link: "#" },
      brandymelville: { value: "Brandy Melville", link: "#" },
      allbrands: { value: "Browse all brands", link: "#" },
    },
  },
};

export const SUPPORT_MENU_NAMES = {
  sustainability: { value: "Sustainability", link: "#" },
  blog: { value: "Blog", link: "#" },
  about: { value: "About", link: "#" },
  selondepop: { value: "Sell on Depop", link: "#" },
  jobs: { value: "Jobs", link: "#" },
  news: { value: "News", link: "#" },
  support: { value: "Support", link: "#" },
  terms: { value: "Terms", link: "#" },
  privacy: { value: "Privacy", link: "#" },
  safety: { value: "Safety", link: "#" },
  sitemaps: { value: "Sitemaps", link: "#" },
  cookies: { value: "Cookies", link: "#" },
};
