export const MENU_NAMES = {
  menswear: {
    name: "Menswear",
    submenu: {
      tops: { name: "Tops", link: "#" },
      bottoms: { name: "Bottoms", link: "#" },
      underwear: { name: "Underwear", link: "#" },
      outerwear: { name: "Outerwear", link: "#" },
      accessories: { name: "Accessories", link: "#" },
      shoes: { name: "Shoes", link: "#" },
    },
  },
  womenswear: {
    name: "Womenswear",
    submenu: {
      tops: { name: "Tops", link: "#" },
      bottoms: { name: "Bottoms", link: "#" },
      dresses: { name: "Dresses", link: "#" },
      lingerie: { name: "Lingerie", link: "#" },
      outerwear: { name: "Outerwear", link: "#" },
      accessories: { name: "Accessories", link: "#" },
      shoes: { name: "Shoes", link: "#" },
      sets: { name: "Sets", link: "#" },
    },
  },
  jewellery: {
    name: "Jewellery",
    submenu: {
      bodyjewellery: { name: "Body jewellery", link: "#" },
      other: { name: "Other", link: "#" },
      bracelets: { name: "Bracelets", link: "#" },
      earrings: { name: "Earrings", link: "#" },
      necklaces: { name: "Neclaces", link: "#" },
      pins: { name: "Pins", link: "#" },
      rings: { name: "Rings", link: "#" },
      watches: { name: "Watches", link: "#" },
    },
  },
  beauty: {
    name: "Beauty",
    submenu: {
      fragrance: { name: "Fragrance", link: "#" },
      hair: { name: "Hair", link: "#" },
      skincare: { name: "Skincare", link: "#" },
      toolsbrushes: { name: "Tools & Brushes", link: "#" },
      bathbody: { name: "Bath & Body", link: "#" },
      makeup: { name: "Makeup", link: "#" },
      other: { name: "Other", link: "#" },
    },
  },
  more: {
    name: "More",
    submenu: {
      art: { name: "Art", link: "#" },
      home: { name: "Home", link: "#" },
      kids: { name: "Kids", link: "#" },
      sportsequipment: { name: "Sports equipment", link: "#" },
      transportation: { name: "Transportation", link: "#" },
      other: { name: "Other", link: "#" },
      booksmagazines: { name: "Books & Magazines", link: "#" },
      film: { name: "Film", link: "#" },
      music: { name: "Music", link: "#" },
      facemasksandcoverings: { name: "Face masks and coverings", link: "#" },
    },
  },
  brands: {
    name: "Brands",
    submenu: {
      nike: { name: "Nike", link: "#" },
      jordan: { name: "Jordan", link: "#" },
      zara: { name: "Zara", link: "#" },
      thenorthface: { name: "The North Face", link: "#" },
      drmartens: { name: "Dr. Martens", link: "#" },
      urbanoutfitters: { name: "Urban Outfitters", link: "#" },
      levis: { name: "Levi's", link: "#" },
      adidas: { name: "Adidas", link: "#" },
      brandymelville: { name: "Brandy Melville", link: "#" },
      allbrands: { name: "Browse all brands", link: "#" },
    },
  },
};

export const SUPPORT_MENU_NAMES = {
  sustainability: { name: "Sustainability", link: "#" },
  blog: { name: "Blog", link: "#" },
  about: { name: "About", link: "#" },
  selondepop: { name: "Sell on Depop", link: "#" },
  jobs: { name: "Jobs", link: "#" },
  news: { name: "News", link: "#" },
  support: { name: "Support", link: "#" },
  terms: { name: "Terms", link: "#" },
  privacy: { name: "Privacy", link: "#" },
  safety: { name: "Safety", link: "#" },
  sitemaps: { name: "Sitemaps", link: "#" },
  cookies: { name: "Cookies", link: "#" },
};
